# Generated by Django 4.1.1 on 2023-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('en_first_title', models.TextField(blank=True, max_length=500, null=True)),
                ('en_second_title', models.TextField(blank=True, max_length=500, null=True)),
                ('en_third_title', models.TextField(blank=True, max_length=500, null=True)),
                ('fr_first_title', models.TextField(blank=True, max_length=500, null=True)),
                ('fr_second_title', models.TextField(blank=True, max_length=500, null=True)),
                ('fr_third_title', models.TextField(blank=True, max_length=500, null=True)),
                ('ar_first_title', models.TextField(blank=True, max_length=500, null=True)),
                ('ar_second_title', models.TextField(blank=True, max_length=500, null=True)),
                ('ar_third_title', models.TextField(blank=True, max_length=500, null=True)),
                ('en_button', models.TextField(blank=True, max_length=40, null=True)),
                ('fr_button', models.TextField(blank=True, max_length=40, null=True)),
                ('ar_button', models.TextField(blank=True, max_length=40, null=True)),
                ('link', models.TextField(blank=True, max_length=500, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='main-shop/e-shop/thumb')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('products', models.ManyToManyField(blank=True, to='shop_manager.product')),
            ],
        ),
    ]
