# Generated by Django 4.1.1 on 2023-03-03 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(blank=True, max_length=15, null=True)),
                ('fr_title', models.CharField(blank=True, max_length=15, null=True)),
                ('ar_title', models.CharField(blank=True, max_length=15, null=True)),
                ('en_value', models.TextField(max_length=1000, null=True)),
                ('fr_value', models.TextField(max_length=1000, null=True)),
                ('ar_value', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_product_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_variant', models.CharField(blank=True, max_length=200, null=True)),
                ('fr_product_title', models.CharField(blank=True, max_length=200, null=True)),
                ('fr_variant', models.CharField(blank=True, max_length=200, null=True)),
                ('ar_product_title', models.CharField(blank=True, max_length=200, null=True)),
                ('ar_variant', models.CharField(blank=True, max_length=200, null=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='shop-manager/product/thumb')),
                ('upc', models.CharField(max_length=20, null=True, unique=True)),
                ('sku', models.CharField(max_length=20, null=True, unique=True)),
                ('tag', models.CharField(blank=True, default='tag', max_length=500)),
                ('review_rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('sell_rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('size', models.CharField(blank=True, max_length=80, null=True)),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('features', models.ManyToManyField(blank=True, to='shop_manager.feature')),
            ],
        ),
    ]
